type ExerciseWithVideo = {
    name: string;
    videoUrl?: string | null;
};

const exerciseVideoByName: Record<string, string> = {
    '90/90 hip switches': '/exercise-videos/90-90-hip-switches.mp4',
    'ankle mobility rocks (knee-to-wall)': '/exercise-videos/ankle-rocks.mp4',
    'ankle rocks': '/exercise-videos/ankle-rocks.mp4',
    'arm circles': '/exercise-videos/arm-circles.mp4',
    'arm swings': '/exercise-videos/arm-swings.mp4',
    'band chest press': '/exercise-videos/band-chest-press.mp4',
    'band face pull': '/exercise-videos/band-face-pull.mp4',
    'band pull-apart': '/exercise-videos/band-pull-apart.mp4',
    'band row': '/exercise-videos/band-row.mp4',
    'bench dips': '/exercise-videos/chair-triceps-dips.mp4',
    'bird dog': '/exercise-videos/bird-dog-reach.mp4',
    'bird dog reach': '/exercise-videos/bird-dog-reach.mp4',
    'bodyweight squat': '/exercise-videos/tempo-bodyweight-squat.mp4',
    'box squat to chair (controlled)': '/exercise-videos/sit-to-stand-squat.mp4',
    'bulgarian split squat': '/exercise-videos/bulgarian-split-squat.mp4',
    'cat-cow spinal flow': '/exercise-videos/cat-cow-spinal-flow.mp4',
    'cat-camel (spine mobility)': '/exercise-videos/cat-cow-spinal-flow.mp4',
    'cat–cow': '/exercise-videos/cat-cow-spinal-flow.mp4',
    'cat–cow (slow)': '/exercise-videos/cat-cow-spinal-flow.mp4',
    'chair triceps dips': '/exercise-videos/chair-triceps-dips.mp4',
    'chest stretch against wall': '/exercise-videos/chest-stretch-against-wall.mp4',
    "child's pose": '/exercise-videos/childs-pose.mp4',
    'child’s pose': '/exercise-videos/childs-pose.mp4',
    'child’s pose with reach (lat stretch)': '/exercise-videos/child-pose-lat-reach.mp4',
    'close-grip push-up': '/exercise-videos/close-grip-push-up.mp4',
    'dead bug activation': '/exercise-videos/dead-bug-activation.mp4',
    'dead bug': '/exercise-videos/dead-bug-activation.mp4',
    'decline push-up': '/exercise-videos/decline-push-up.mp4',
    'dumbbell biceps curl': '/exercise-videos/dumbbell-biceps-curl.mp4',
    'dumbbell bench press': '/exercise-videos/dumbbell-bench-press.mp4',
    'dumbbell glute bridge': '/exercise-videos/dumbbell-glute-bridge.mp4',
    'dumbbell lateral raise': '/exercise-videos/dumbbell-lateral-raise.mp4',
    'dumbbell step-up': '/exercise-videos/dumbbell-step-up.mp4',
    'dumbbell triceps extension': '/exercise-videos/dumbbell-triceps-extension.mp4',
    'dumbbell walking lunge': '/exercise-videos/dumbbell-walking-lunge.mp4',
    'dumbbell floor press': '/exercise-videos/dumbbell-floor-press.mp4',
    'dumbbell goblet squat': '/exercise-videos/goblet-squat.mp4',
    'dumbbell romanian deadlift': '/exercise-videos/dumbbell-romanian-deadlift.mp4',
    'dumbbell shoulder press': '/exercise-videos/dumbbell-shoulder-press.mp4',
    'dumbbell overhead press': '/exercise-videos/dumbbell-shoulder-press.mp4',
    'dumbbell shoulder press (seated/standing)': '/exercise-videos/dumbbell-shoulder-press.mp4',
    'figure-four glute stretch': '/exercise-videos/figure-four-glute-stretch.mp4',
    'forearm plank': '/exercise-videos/forearm-plank.mp4',
    'front plank (full)': '/exercise-videos/forearm-plank.mp4',
    'front plank (knees)': '/exercise-videos/forearm-plank.mp4',
    'glute bridge': '/exercise-videos/glute-bridge-v2.mp4',
    'glute bridge march activation': '/exercise-videos/glute-bridge-march-activation.mp4',
    'glute bridge march': '/exercise-videos/glute-bridge-march-activation.mp4',
    'goblet squat': '/exercise-videos/goblet-squat.mp4',
    'goblet squat with dumbbell': '/exercise-videos/goblet-squat.mp4',
    'half-kneeling hip flexor stretch': '/exercise-videos/hip-flexor-lunge-stretch.mp4',
    'half-kneeling dumbbell press': '/exercise-videos/half-kneeling-dumbbell-press.mp4',
    'hamstring walkout': '/exercise-videos/hamstring-walkout.mp4',
    'hamstring stretch (lying with towel)': '/exercise-videos/hamstring-strap-stretch.mp4',
    'hip circles': '/exercise-videos/hip-circles.mp4',
    'hip hinge drill': '/exercise-videos/hip-hinge-drill.mp4',
    'hip flexor lunge stretch': '/exercise-videos/hip-flexor-lunge-stretch.mp4',
    'hip flexor stretch (half-kneeling)': '/exercise-videos/hip-flexor-lunge-stretch.mp4',
    'hip thrust': '/exercise-videos/hip-thrust.mp4',
    'hip thrust (shoulders on bench)': '/exercise-videos/hip-thrust.mp4',
    'incline push-up': '/exercise-videos/incline-push-up.mp4',
    'incline push-up (hands on bench/chair)': '/exercise-videos/incline-push-up.mp4',
    'inchworm walkout': '/exercise-videos/inchworm-walkout.mp4',
    'knee push-up': '/exercise-videos/knee-push-up.mp4',
    'lateral lunge': '/exercise-videos/lateral-lunge.mp4',
    'lateral lunge reach': '/exercise-videos/lateral-lunge-reach.mp4',
    'low-impact jumping jacks': '/exercise-videos/low-impact-jumping-jacks.mp4',
    'low-impact mountain climbers': '/exercise-videos/slow-mountain-climber.mp4',
    'low step-up': '/exercise-videos/low-step-up.mp4',
    'neck circles': '/exercise-videos/neck-circles.mp4',
    'one-arm dumbbell row': '/exercise-videos/one-arm-dumbbell-row.mp4',
    'pike push-up': '/exercise-videos/pike-push-up.mp4',
    'bear hover': '/exercise-videos/bear-hover.mp4',
    'hollow body tuck': '/exercise-videos/hollow-body-tuck.mp4',
    'modified pilates roll-up': '/exercise-videos/modified-pilates-roll-up.mp4',
    'pallof press': '/exercise-videos/pallof-press.mp4',
    'pilates hundred': '/exercise-videos/pilates-hundred.mp4',
    'pilates double-leg stretch': '/exercise-videos/pilates-double-leg-stretch.mp4',
    'pilates saw': '/exercise-videos/pilates-saw.mp4',
    'pilates single-leg stretch': '/exercise-videos/pilates-single-leg-stretch.mp4',
    'pilates spine stretch forward': '/exercise-videos/pilates-spine-stretch-forward.mp4',
    'pilates swimming': '/exercise-videos/pilates-swimming.mp4',
    'plank shoulder tap': '/exercise-videos/plank-shoulder-tap.mp4',
    'plank': '/exercise-videos/forearm-plank.mp4',
    'prone cobra hold': '/exercise-videos/prone-cobra-hold.mp4',
    'prone y-t-w raise': '/exercise-videos/prone-y-t-w-raise.mp4',
    'reverse lunge': '/exercise-videos/reverse-lunge.mp4',
    'reverse lunges': '/exercise-videos/reverse-lunge.mp4',
    'reverse lunges (bodyweight)': '/exercise-videos/reverse-lunge.mp4',
    'reverse snow angel': '/exercise-videos/reverse-snow-angel.mp4',
    'romanian deadlift with dumbbells': '/exercise-videos/dumbbell-romanian-deadlift.mp4',
    'scapular wall slides': '/exercise-videos/scapular-wall-slides.mp4',
    'shoulder wall slides': '/exercise-videos/scapular-wall-slides.mp4',
    'seated glute stretch': '/exercise-videos/seated-glute-stretch.mp4',
    'seated hamstring stretch': '/exercise-videos/seated-hamstring-stretch.mp4',
    'shoulder cars': '/exercise-videos/shoulder-cars.mp4',
    'shoulder cross-body stretch': '/exercise-videos/shoulder-cross-body-stretch.mp4',
    'shoulder rolls': '/exercise-videos/shoulder-rolls.mp4',
    'single-leg glute bridge': '/exercise-videos/single-leg-glute-bridge.mp4',
    'side lying leg raises': '/exercise-videos/side-lying-leg-raises.mp4',
    'side-lying leg lift': '/exercise-videos/side-lying-leg-raises.mp4',
    'side plank': '/exercise-videos/side-plank.mp4',
    'side plank (full)': '/exercise-videos/side-plank.mp4',
    'side plank (knees)': '/exercise-videos/side-plank.mp4',
    'sit-to-stand squat': '/exercise-videos/sit-to-stand-squat.mp4',
    'sit-to-stand (chair)': '/exercise-videos/sit-to-stand-squat.mp4',
    'split squat': '/exercise-videos/split-squat.mp4',
    'split stance squat (static)': '/exercise-videos/split-squat.mp4',
    'squat-to-stand prying stretch': '/exercise-videos/squat-to-stand-prying-stretch.mp4',
    'standard push-up': '/exercise-videos/standard-push-up.mp4',
    'standing calf raise': '/exercise-videos/standing-calf-raise.mp4',
    'standing calf stretch': '/exercise-videos/standing-calf-stretch.mp4',
    'standing hamstring stretch': '/exercise-videos/standing-hamstring-stretch.mp4',
    'standing quad stretch': '/exercise-videos/standing-quad-stretch.mp4',
    'superman': '/exercise-videos/superman.mp4',
    'thoracic open book rotation': '/exercise-videos/thoracic-open-book-rotation.mp4',
    'tempo bodyweight squat': '/exercise-videos/tempo-bodyweight-squat.mp4',
    'tempo squat (slow lower)': '/exercise-videos/tempo-bodyweight-squat.mp4',
    'torso twists (standing)': '/exercise-videos/torso-twists-standing.mp4',
    'thoracic rotation (open book)': '/exercise-videos/thoracic-open-book-rotation.mp4',
    'wall calf stretch': '/exercise-videos/standing-calf-stretch.mp4',
    'wall push-up': '/exercise-videos/wall-push-up.mp4',
    'wall sit': '/exercise-videos/wall-sit.mp4',
    'worlds greatest stretch': '/exercise-videos/worlds-greatest-stretch.mp4',
    "world's greatest stretch": '/exercise-videos/worlds-greatest-stretch.mp4',
    'clamshell': '/exercise-videos/clamshell.mp4',
    'cross-body mountain climber': '/exercise-videos/cross-body-mountain-climber.mp4',
    'donkey kick': '/exercise-videos/donkey-kick.mp4',
    'fire hydrant': '/exercise-videos/fire-hydrant.mp4',
    'heel taps': '/exercise-videos/heel-taps.mp4',
    'lateral shuffle reach': '/exercise-videos/lateral-shuffle-reach.mp4',
    'low-impact skater step': '/exercise-videos/low-impact-skater-step.mp4',
    'reverse crunch': '/exercise-videos/reverse-crunch.mp4',
    'slow mountain climber': '/exercise-videos/slow-mountain-climber.mp4',
    'squat to calf raise': '/exercise-videos/squat-to-calf-raise.mp4',
    'bear crawl': '/exercise-videos/bear-crawl.mp4',
    'boxing cross-body combo': '/exercise-videos/boxing-cross-body-combo.mp4',
    'child pose lat reach': '/exercise-videos/child-pose-lat-reach.mp4',
    'couch stretch': '/exercise-videos/couch-stretch.mp4',
    'inchworm to plank': '/exercise-videos/inchworm-to-plank.mp4',
    'plank jack': '/exercise-videos/plank-jack.mp4',
    'reverse lunge to knee drive': '/exercise-videos/reverse-lunge-to-knee-drive.mp4',
    'skater hop': '/exercise-videos/skater-hop.mp4',
    'skater hops': '/exercise-videos/skater-hop.mp4',
    'squat thrust': '/exercise-videos/squat-thrust.mp4',
    'step-back burpee': '/exercise-videos/step-back-burpee.mp4',
    '90/90 breathing reset': '/exercise-videos/90-90-breathing-reset.mp4',
    'doorway pec stretch': '/exercise-videos/doorway-pec-stretch.mp4',
    'hamstring strap stretch': '/exercise-videos/hamstring-strap-stretch.mp4',
    'jog in place (fallback only)': '/exercise-videos/jog-in-place.mp4',
    'march in place (fallback only)': '/exercise-videos/march-in-place.mp4',
    'shadow boxing (fallback only)': '/exercise-videos/shadow-boxing.mp4',
    'stair walk (fallback only)': '/exercise-videos/stair-walk.mp4',
    'step jacks (fallback only)': '/exercise-videos/step-jacks.mp4',
    'supine twist': '/exercise-videos/supine-twist.mp4',
    'thread-the-needle stretch': '/exercise-videos/thread-the-needle-stretch.mp4',
    'treadmill walk-jog intervals (fallback only)': '/exercise-videos/treadmill-walk-jog-intervals.mp4',
    'treadmill incline walk': '/exercise-videos/treadmill-walk-jog-intervals.mp4',
    'barbell back squat': '/exercise-videos/barbell-back-squat.mp4',
    'barbell front squat': '/exercise-videos/barbell-front-squat.mp4',
    'barbell hip thrust': '/exercise-videos/barbell-hip-thrust.mp4',
    'barbell romanian deadlift': '/exercise-videos/barbell-romanian-deadlift.mp4',
    'barbell bench press': '/exercise-videos/barbell-bench-press.mp4',
    'barbell bent-over row': '/exercise-videos/barbell-bent-over-row.mp4',
    'incline dumbbell press': '/exercise-videos/incline-dumbbell-press.mp4',
    'seated dumbbell shoulder press': '/exercise-videos/dumbbell-shoulder-press.mp4',
    'farmer carry': '/exercise-videos/farmer-carry.mp4',
    'kettlebell goblet squat': '/exercise-videos/kettlebell-goblet-squat.mp4',
    'kettlebell deadlift': '/exercise-videos/kettlebell-deadlift.mp4',
    'kettlebell swing': '/exercise-videos/kettlebell-swing.mp4',
    'kettlebell suitcase deadlift': '/exercise-videos/kettlebell-suitcase-deadlift.mp4',
    'one-arm kettlebell row': '/exercise-videos/one-arm-kettlebell-row.mp4',
    'kettlebell floor press': '/exercise-videos/kettlebell-floor-press.mp4',
    'kettlebell halo': '/exercise-videos/kettlebell-halo.mp4',
    'kettlebell reverse lunge': '/exercise-videos/kettlebell-reverse-lunge.mp4',
    'kettlebell suitcase carry': '/exercise-videos/kettlebell-suitcase-carry.mp4',
    'suitcase carry (light)': '/exercise-videos/kettlebell-suitcase-carry.mp4',
    'step-up (low step)': '/exercise-videos/low-step-up.mp4',
    'y-t-w raises (light)': '/exercise-videos/prone-y-t-w-raise.mp4',
};

export function getExerciseVideoUrl(exercise: ExerciseWithVideo) {
    return exercise.videoUrl ?? exerciseVideoByName[exercise.name.trim().toLowerCase()] ?? null;
}

export function withExerciseVideoUrl<T extends ExerciseWithVideo>(exercise: T): T {
    return {
        ...exercise,
        videoUrl: getExerciseVideoUrl(exercise),
    };
}
